package Form;

import DataBase.ConnectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Sytru
 */
public class FBFReportDay extends javax.swing.JInternalFrame {
    ConnectDB cn = new ConnectDB();
    Connection conn;
    public FBFReportDay() {
        initComponents();
        ngayBaoCao.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        ngayBaoCao = new com.toedter.calendar.JDateChooser();
        reportButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Báo Cáo Doanh Thu Sân Bóng Theo Ngày");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setText("BÁO CÁO DOANH THU SÂN BÓNG THEO NGÀY");

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sân Bóng", "Số Lần Đặt", "Doanh Thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reportTable);

        reportButton.setText("Xác Nhận");
        reportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportButtonMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(41, 128, 185));
        jLabel2.setText("Chọn Ngày");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngayBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reportButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngayBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static DefaultCategoryDataset extractDataFromTable(JTable table) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        int rowCount = table.getRowCount();
        for (int i = 0; i < rowCount - 1; i++) {
            Object sanBong = table.getValueAt(i, 0);
            Object soLanDatString = table.getValueAt(i, 1);
            double doanhThu = Double.parseDouble(table.getValueAt(i, 2).toString());
            Number soLanDat = Integer.parseInt((String) soLanDatString);
            dataset.addValue(doanhThu, "Doanh thu", (String) sanBong);
        }
        return dataset;
    }
        
    private void reportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportButtonMouseClicked
        DefaultTableModel dm = (DefaultTableModel)reportTable.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
        DefaultTableCellRenderer stringRenderer = (DefaultTableCellRenderer)
        reportTable.getDefaultRenderer(String.class);
        stringRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableModel model = (DefaultTableModel) reportTable.getModel();
        String tenSan = "", maSan = "";
        Integer soLanDat = 0;
        Integer doanhThu = 0;
        Integer tongSLD = 0;
        Integer tongDT = 0;
        Date ngaybaocaotemp = ngayBaoCao.getDate();
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngayBaoCao = outputFormat.format(ngaybaocaotemp);
        String select_FBF = "Select * from SanBong";
        try {
            conn = cn.getConnection();
            PreparedStatement pst = conn.prepareStatement(select_FBF);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                tenSan = rs.getString("TenSan");
                maSan = rs.getString("MaSan");
                String select_PDS = "Select * from PhieuDatSan WHERE MaSan = ? AND CAST(GioBD AS DATE) = ? AND TrangThai != ?";
                PreparedStatement stmt = conn.prepareStatement(select_PDS);
                stmt.setString(1, maSan);
                stmt.setString(2, ngayBaoCao);
                stmt.setString(3, "Đã Hủy");
                ResultSet pds = stmt.executeQuery();
                while(pds.next()){
                    soLanDat = soLanDat + 1;
                    String maPDS = pds.getString("MaPhieuDat");
                    String select_HD = "Select * from HoaDon WHERE MaPhieuDat = ?";
                    PreparedStatement pst2 = conn.prepareStatement(select_HD);
                    pst2.setString(1, maPDS);
                    ResultSet hd = pst2.executeQuery();
                    while(hd.next()){
                        doanhThu = doanhThu + hd.getInt("TienSan");
                    }
                    String[] line = { tenSan, String.valueOf(soLanDat), String.valueOf(doanhThu) };
                    model.addRow(line);
                    tongDT = tongDT + doanhThu;
                    tongSLD = tongSLD + soLanDat;
                    tenSan = ""; maSan = "";
                    soLanDat = 0;
                    doanhThu = 0;
                }
            }
            String[] line = { "Tổng", String.valueOf(tongSLD), String.valueOf(tongDT) };
            model.addRow(line);
            rs.close();
            pst.close();
            conn.close();
       } catch (Exception ex) {
          ex.printStackTrace();
       }
        
        DefaultCategoryDataset dataset = extractDataFromTable(reportTable);
        // Tạo biểu đồ cột
        JFreeChart chart = ChartFactory.createBarChart(
                "Biểu đồ doanh thu sân bóng theo ngày", // Tiêu đề biểu đồ
                "Sân bóng", // Nhãn trục x
                "Doanh Thu", // Nhãn trục y
                dataset, // Dataset
                PlotOrientation.VERTICAL, // Hướng biểu đồ
                true, // Hiển thị legent
                true, // Hiển thị tooltips
                false // Không hiển thị URLs
        );
        ChartFrame frame = new ChartFrame("Biểu đồ doanh thu sân bóng theo ngày", chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_reportButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser ngayBaoCao;
    private javax.swing.JButton reportButton;
    private javax.swing.JTable reportTable;
    // End of variables declaration//GEN-END:variables
}
