package Form;

import DataBase.ConnectDB;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class Provider extends javax.swing.JInternalFrame {
    ConnectDB cn = new ConnectDB();
    Connection conn;
    String CODE = "INSERT", ID;
    
    public void SelectAllNCC(){
        String select_NCC = "Select * from NhaCungCap";
        try{
            conn = cn.getConnection();
            PreparedStatement pst = conn.prepareStatement(select_NCC);
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) nccTable.getModel();
            String ID, TenNCC, SDTNCC, DCNCC, GhiChu;
            while(rs.next()){
               ID = rs.getString("MaNCC");
               TenNCC = rs.getString("TenNCC");
               SDTNCC = rs.getString("SDT");
               DCNCC = rs.getString("DiaChi");
               if(!rs.getString("GhiChu").equals("PAUSED")){
                    GhiChu = rs.getString("GhiChu");
                    String[] ncc = {ID, TenNCC, SDTNCC, DCNCC, GhiChu};
                    model.addRow(ncc);
               }
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public Provider() {
        initComponents();
        ImageIcon img = new ImageIcon("D:\\Football_Filed_Managerment\\src\\images\\icons/—Pngtree—football field plan_4710125 (1).png");
        this.setFrameIcon(img);
        SelectAllNCC();
        ColumnsAutoSizer.sizeColumnsToFit(nccTable);
        nccTable.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table =(JTable) mouseEvent.getSource();
                java.awt.Point point = mouseEvent.getPoint();
                int row = table.rowAtPoint(point);
                if(row == -1){
                    return;
                }
                String nccID = nccTable.getModel().getValueAt(row, 0).toString();
                if (mouseEvent.getClickCount() == 1 && table.getSelectedRow() != -1) {
                    try {
                        conn = cn.getConnection();
                        String select_1NCC = "Select * from NhaCungCap where MaNCC = ?";
                        PreparedStatement pst3 = conn.prepareStatement(select_1NCC);
                        pst3.setString(1, nccID);
                        ResultSet ncc = pst3.executeQuery();
                        if(ncc.next()){
                            tennccTxt.setText(ncc.getString("TenNCC").trim());
                            sdtnccTxt.setText(ncc.getString("SDT").trim());
                            dcnccTxt.setText(ncc.getString("DiaChi").trim()); 
                            ghichuTxt.setText(ncc.getString("GhiChu"));
                        }
                        CODE = "UPDATE";
                        ID = nccID;
                    } catch (Exception e){
                        e.printStackTrace();
                    }
                }   
            }
        });
    }
    public void Reset(){
        DefaultTableModel dm = (DefaultTableModel)nccTable.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged(); 
        SelectAllNCC();
        tennccTxt.setText("");
        dcnccTxt.setText("");
        sdtnccTxt.setText("");
        ghichuTxt.setText("");
        CODE = "INSERT";
        ColumnsAutoSizer.sizeColumnsToFit(nccTable);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tennccTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dcnccTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sdtnccTxt = new javax.swing.JTextField();
        ghichuTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        saveNCC = new javax.swing.JButton();
        addNCC = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        nccTable = new javax.swing.JTable();

        setTitle("Quản Lý Nhà Cung Cấp");

        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setText("Tên Nhà Cung Cấp");

        tennccTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 1, true));
        tennccTxt.setPreferredSize(new java.awt.Dimension(0, 21));

        jLabel2.setForeground(new java.awt.Color(41, 128, 185));
        jLabel2.setText("Địa Chỉ Nhà Cung Cấp");

        dcnccTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 1, true));
        dcnccTxt.setPreferredSize(new java.awt.Dimension(0, 21));

        jLabel3.setForeground(new java.awt.Color(41, 128, 185));
        jLabel3.setText("SDT Nhà Cung Cấp");

        sdtnccTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 1, true));
        sdtnccTxt.setPreferredSize(new java.awt.Dimension(0, 21));

        ghichuTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 1, true));
        ghichuTxt.setPreferredSize(new java.awt.Dimension(0, 21));

        jLabel4.setForeground(new java.awt.Color(41, 128, 185));
        jLabel4.setText("Ghi Chú");

        searchTxt.setText("Nhập để tìm kiếm");
        searchTxt.setToolTipText("");
        searchTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 1, true));
        searchTxt.setPreferredSize(new java.awt.Dimension(0, 21));
        searchTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTxtMouseClicked(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });

        saveNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/022-save.png"))); // NOI18N
        saveNCC.setText("Lưu");
        saveNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveNCCMouseClicked(evt);
            }
        });

        addNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/056-plus.png"))); // NOI18N
        addNCC.setText("Thêm");
        addNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNCCMouseClicked(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/058-error.png"))); // NOI18N
        cancelButton.setText("Hủy");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        nccTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Số Điện Thoại Nhà Cung Cấp", "Địa Chỉ Nhà Cung Cấp", "Ghi Chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(nccTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(addNCC)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(26, 26, 26)
                                        .addComponent(tennccTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(24, 24, 24)
                                        .addComponent(sdtnccTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ghichuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcnccTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveNCC)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tennccTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dcnccTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sdtnccTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ghichuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNCC)
                    .addComponent(cancelButton)
                    .addComponent(saveNCC))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTxtMouseClicked
        searchTxt.setText("");
    }//GEN-LAST:event_searchTxtMouseClicked
    
    public void filter(String query){
        DefaultTableModel dm = (DefaultTableModel) nccTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
        nccTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        String query = searchTxt.getText().trim();
        filter(query);
    }//GEN-LAST:event_searchTxtKeyReleased
    

    private void addNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNCCMouseClicked
        try {
            tennccTxt.setText("");
            dcnccTxt.setText("");
            sdtnccTxt.setText("");
            ghichuTxt.setText("");
            CODE = "INSERT";
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_addNCCMouseClicked
    
    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked
    
    public void insertNCC(String tenNCC, String sdtNCC, String dcNCC, String ghichu){
        try{
            String insert = "INSERT INTO NhaCungCap(TenNCC, SDT, DiaChi, GhiChu) VALUES(?,?,?,?)";
            conn = cn.getConnection();
            PreparedStatement pst2 = conn.prepareStatement(insert);
            pst2.setString(1, tenNCC);
            pst2.setString(2, sdtNCC);
            pst2.setString(3, dcNCC);
            pst2.setString(4, ghichu);
            pst2.execute();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void updateNCC(String tenNCC, String sdtNCC, String dcNCC, String ghichu, String maNCC){
        try{
            String update = "UPDATE NhaCungCap SET TenNCC = ?, SDT = ?, DiaChi = ?, GhiChu = ? WHERE MaNCC = ?";
            conn = cn.getConnection();
            PreparedStatement pst2 = conn.prepareStatement(update);
            pst2.setString(1, tenNCC);
            pst2.setString(2, sdtNCC);
            pst2.setString(3, dcNCC);
            pst2.setString(4, ghichu);
            pst2.setString(5, maNCC);
            pst2.execute();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    private void saveNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveNCCMouseClicked
        String tenNCC = tennccTxt.getText().trim();
        String sdtNCC = sdtnccTxt.getText().trim();
        String dcNCC = dcnccTxt.getText().trim();
        String ghichu = ghichuTxt.getText().trim();
        StringBuffer sb = new StringBuffer();
        if(tenNCC.length() == 0){
            sb.append("Tên nhà cung cấp không được để trống!\n");
        }
        if(sdtNCC.length() == 0){
            sb.append("Số điện thoại nhà cung cấp không được để trống!\n");
        }
        if(Validate.notNumber(sdtNCC) == true || sdtNCC.length() != 10 ){
            sb.append("Số điện thoại nhà cung cấp không đúng định dạng!\n");
        }
        if(dcNCC.length() == 0){
            sb.append("Địa chỉ nhà cung cấp không được để trống!\n");
        }
        String select_NCC = "Select * from NhaCungCap where MaNCC != ?";
        try{
            conn = cn.getConnection();
            PreparedStatement pst = conn.prepareStatement(select_NCC);
            pst.setString(1, ID);
            ResultSet ncc = pst.executeQuery();
            while(ncc.next()){
                if(ncc.getString("TenNCC").trim().equals(tenNCC) == true){
                    sb.append("Nhà Cung Cấp đã tồn tại!\n");
                }
                if(ncc.getString("SDT").trim().equals(sdtNCC) == true){
                    sb.append("Số điện thoại bị trùng !\n");
                }
            }
        } catch(Exception e){
            e.printStackTrace();
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString());
            return;
        }
        if( CODE.equals("INSERT") == true){
            insertNCC(tenNCC,sdtNCC,dcNCC,ghichu);
            JOptionPane.showMessageDialog(this, "Đã Thêm Nhà Cung Cấp Thành Công");
            Reset();
        }
        if( CODE.equals("UPDATE") == true){
            updateNCC(tenNCC,sdtNCC,dcNCC,ghichu,ID);
            JOptionPane.showMessageDialog(this, "Chỉnh Sửa Thông Tin Nhà Cung Cấp Thành Công");
            Reset();
        }
    }//GEN-LAST:event_saveNCCMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNCC;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dcnccTxt;
    private javax.swing.JTextField ghichuTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable nccTable;
    private javax.swing.JButton saveNCC;
    private javax.swing.JTextField sdtnccTxt;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField tennccTxt;
    // End of variables declaration//GEN-END:variables
}
